export const EN = {
  title: 'Salvoconducto',
  tagline: 'Give an agent the fewest fields it needs, for one purpose and a set time, with an honest account of what it already saw.',
  prototypeNote: 'Prototype: the Passport, the agents, and the authorization server are simulated in your browser. The cryptography is real; the integration is not.',
  passportNote: 'Illustrative fields, grouped by category as in the AI Passport.',
  logNote: 'The log keeps a salted hash of each value read, not the value itself.',
  docClass: 'Class · Agents',
  stampGranted: 'Granted',
  stampRevoked: 'Revoked',
  stampDenied: 'Denied',
  passportHeading: 'Your AI Passport',
  requestHeading: 'Access request',
  task: 'Task',
  requests: 'Requests',
  purpose: 'purpose',
  expiresIn: 'expires in',
  minimization: 'Minimizing: {n} of {total} fields requested',
  grant: 'Grant',
  editFields: 'Edit fields',
  deny: 'Deny',
  receiptsHeading: 'Live receipts',
  revoke: 'Revoke all',
  proveHeading: 'Revocation, verified',
  proveRun: 'Test it: probe a read now',
  proveDenied: 'DENIED. Token revoked. The next read died at the enforcement point.',
  overAskFlag: 'Out of declared scope — blocked and logged',
  honestyHeading: 'What the agent already saw',
  honestyLine: '{field} entered the agent context and cannot be un-seen.',
  exposureLine: 'Exposure minimized: {count} sensitive field(s), {minutes} min.',
  chainOk: 'Receipt chain intact',
  chainBroken: 'Receipt chain broken',
  restart: 'Restart',
  langToggle: 'Español',
};
