export const ES = {
  title: 'Salvoconducto',
  tagline: 'Dale a un agente los menos campos posibles, para un solo propósito y un tiempo acotado, con una cuenta honesta de lo que ya vio.',
  prototypeNote: 'Prototipo: el Pasaporte, los agentes y el servidor de autorización están simulados en tu navegador. La criptografía es real; la integración no.',
  passportNote: 'Campos ilustrativos, agrupados por categoría como en el Pasaporte de IA.',
  logNote: 'El registro guarda un hash con sal de cada valor leído, no el valor.',
  chooseHint: 'Elige desde tu registro a la izquierda. Puedes compartir menos, nunca más.',
  notRequested: 'no solicitado',
  tapToShare: 'toca para incluir',
  willShare: 'se comparte',
  shared: 'compartido',
  withheld: 'retenido',
  docClass: 'Clase · Agentes',
  stampGranted: 'Concedido',
  stampRevoked: 'Revocado',
  stampDenied: 'Denegado',
  passportHeading: 'Tu Pasaporte de IA',
  requestHeading: 'Solicitud de acceso',
  task: 'Tarea',
  requests: 'Pide',
  purpose: 'propósito',
  expiresIn: 'vence en',
  minimization: 'Minimizando: {n} de {total} campos solicitados',
  grant: 'Conceder',
  editFields: 'Editar campos',
  deny: 'Denegar',
  receiptsHeading: 'Recibos en vivo',
  revoke: 'Revocar todo',
  proveHeading: 'Revocación, verificada',
  proveRun: 'Compruébalo: sondea una lectura ahora',
  proveDenied: 'DENEGADO. Token revocado. La siguiente lectura murió en el punto de control.',
  overAskFlag: 'Fuera del alcance declarado — bloqueado y registrado',
  honestyHeading: 'Lo que el agente ya vio',
  honestyLine: '{field} entró al contexto del agente y no se puede "des-ver".',
  exposureLine: 'Exposición minimizada: {count} campo(s) sensible(s), {minutes} min.',
  chainOk: 'Cadena de recibos íntegra',
  chainBroken: 'Cadena de recibos rota',
  restart: 'Reiniciar',
  langToggle: 'English',
};
